### ISSUE TITLE
Add support for fetching total members from discord server

### ISSUE THREAD

**Issue by Bhupesh-V** [developersIndia/metrics#3]
### Feature details?

We currently only have metrics from Reddit, it would be nice to have similar or some kind of data from our discord server as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imkaka** [comment]
I would love to work on this, please assign it to me.

**Comment by Bhupesh-V** [comment]
> I would love to work on this, please assign it to me.

You got it!
LMK if any help/suggestions is required.

**Comment by imkaka** [comment]
Hey @Bhupesh-V 
a couple of questions.
1. How exactly is this to be designed currently, the Reddit script is writing to a file in `data/`, we want to have another script that writes to a new file or wants to modify the same file.
2. What all data from discord is needed for this, do we have any experience building with discord and what all APIs should I explore?

**Comment by Bhupesh-V** [comment]
1. We can modify the same file, just add a new JSON Key like `discordTotalMembers`.
2. No, we haven't researched about the API. We only need the total members count for now. If using the API is not possible, you can look at this hack to fetch data using an invite link https://stackoverflow.com/questions/71566064/how-to-get-total-member-count-of-any-discord-server.

**Comment by imkaka** [comment]
PR is ready for review, LMK if we need to change anything.
